#!/usr/bin/env python3
"""Generates src/logo-art.ts from the official YukiOshi emblem.

Terminals cannot draw vector graphics, so the emblem and the "YukiOshi" wordmark are
traced from assets/brand/yukioshi-code-emblem-dark.png into quadrant block characters
(2x2 pixels per cell). Each cell records which part of the logo it shows, so the TUI can
colour it from the active theme and keep it visible on light and dark backgrounds.

Requires Pillow. Run from the repository root:
    python3 packages/tui/script/generate-logo.py
"""

import json
import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[3]
SOURCE = ROOT / "assets/brand/yukioshi-code-emblem-dark.png"
OUTPUT = ROOT / "packages/tui/src/logo-art.ts"

BACKGROUND = (1, 6, 20)
# Regions of the 1254x1254 source image.
EMBLEM_BOX = (281, 197, 973, 680)
WORDMARK_BOX = (162, 728, 1087, 867)

QUADRANTS = {0: " ", 1: "▘", 2: "▝", 3: "▀", 4: "▖", 5: "▌", 6: "▞", 7: "▛",
             8: "▗", 9: "▚", 10: "▐", 11: "▜", 12: "▄", 13: "▙", 14: "▟", 15: "█"}


def lit(pixel):
    return sum(abs(a - b) for a, b in zip(pixel, BACKGROUND)) > 90


def part(pixel):
    """w: white crystal and "Yuki", i: pale ice blue, b: brand blue."""
    high, low = max(pixel), min(pixel)
    saturation = (high - low) / high if high else 0
    if saturation < 0.35:
        return "w"  # white, including the grey anti-aliased edges of white shapes
    if saturation < 0.55 and high > 150:
        return "i"
    return "b"


def trace(image, box, rows):
    crop = image.crop(box)
    width, height = crop.size
    # A terminal cell is about twice as tall as it is wide, and holds 2x2 quadrant pixels.
    cols = round(2 * rows * width / height)
    pixels = crop.resize((cols * 2, rows * 2), Image.LANCZOS).load()
    lines, parts = [], []
    for row in range(rows):
        line, colours = "", ""
        for col in range(cols):
            mask, votes = 0, {}
            for bit, (dx, dy) in enumerate(((0, 0), (1, 0), (0, 1), (1, 1))):
                pixel = pixels[col * 2 + dx, row * 2 + dy]
                if lit(pixel):
                    mask |= 1 << bit
                    key = part(pixel)
                    votes[key] = votes.get(key, 0) + 1
            line += QUADRANTS[mask]
            colours += max(votes, key=lambda key: (votes[key], key == "w")) if votes else " "
        trimmed = line.rstrip()
        lines.append(trimmed)
        parts.append(colours[: len(trimmed)])
    return {"lines": lines, "parts": parts}


def main():
    image = Image.open(SOURCE).convert("RGB")
    art = {
        "emblemLarge": trace(image, EMBLEM_BOX, 12),
        "emblemMedium": trace(image, EMBLEM_BOX, 10),
        "wordmark": trace(image, WORDMARK_BOX, 5),
    }
    body = [
        "// Generated by packages/tui/script/generate-logo.py from",
        "// assets/brand/yukioshi-code-emblem-dark.png. Do not edit by hand.",
        "",
        "export type LogoPart = \"w\" | \"i\" | \"b\" | \" \"",
        "",
        "/** Quadrant-block lines, and per character which logo part it shows: w white, i ice blue, b brand blue. */",
        "export type LogoArt = { readonly lines: readonly string[]; readonly parts: readonly string[] }",
        "",
    ]
    for name, value in art.items():
        body.append(f"export const {name}: LogoArt = {json.dumps(value, ensure_ascii=False, indent=2)}")
        body.append("")
    OUTPUT.write_text("\n".join(body))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
