// Generated by packages/tui/script/generate-logo.py from
// assets/brand/yukioshi-code-emblem-dark.png. Do not edit by hand.

export type LogoPart = "w" | "i" | "b" | " "

/** Quadrant-block lines, and per character which logo part it shows: w white, i ice blue, b brand blue. */
export type LogoArt = { readonly lines: readonly string[]; readonly parts: readonly string[] }

export const emblemLarge: LogoArt = {
  "lines": [
    "                ▟▙",
    "               ▟██▙",
    "       ▄▖   ▐▄ ▝██▘ ▄▙   ▗▄",
    "     ▄██▛▐█▙▞██ ██ ▟▛▙▟█▌▜██▄",
    "  ▗▟██▛▘  ▀███▙▖██▗▟███▀  ▝▜██▙▖",
    "▗▟██▀▘ ▄▄█▙▄▟▟██████▙▙▄▟█▄▄ ▝▀██▙▄",
    "▀██▙▄  ▀▜██▀▀▜██████▛▀▀██▛▀  ▄▟██▀",
    "  ▀▜██▄   ▄▟██▛▀██▀▜██▙▄   ▄██▛▀",
    "    ▝▜██▖▐██▜▟█ ██ █▙▛██▌▗██▛▘",
    "      ▝▜▛▝▘ ▟▀▘▗██▖▝▀▙ ▝▘▜▀▘",
    "               ▜██▛",
    "                ▜▛"
  ],
  "parts": [
    "                wi",
    "               wwib",
    "       bb   bb wiib bb   bb",
    "     bbbbbbbbbb ii bbbbbbbbbb",
    "  bbbbbb  bbbwwbwwbwwbbb  bbbbbb",
    "bbbbbb wwwwwwwwwwwwwwwwwwwb bbbbbb",
    "bbbbb  wiibbbbwwwwwwbbbbbbb  bbbbb",
    "  bbbbb   bbbwwiwwbwwbbb   bbbbb",
    "    bbbbbbbbbbb wi bbbbbbbbbbb",
    "      bbbbb bbbwibbbbb bbbbb",
    "               wwbb",
    "                wb"
  ]
}

export const emblemMedium: LogoArt = {
  "lines": [
    "             ▗█▖",
    "             ███",
    "     ▄█▌▄▄▐█▖▐█▌▗█▌▄▄▐█▄",
    "  ▗▟██▀ ▀███▙▐█▌▟███▀ ▀██▙▖",
    "▄▟█▛▀ ▄▄█▄▟███████▙▄▟▄▄ ▀▜█▙▄",
    "▀██▙▖ ▀▜█▀▜▜█████▛▛▀█▀▀ ▗▟██▀",
    "  ▝▜█▙▄ ▄███▛▐█▌▜███▄ ▄▟█▛▘",
    "    ▝▜█▌█▀▐█▘▐█▌▝█▖▀█▐█▛▘",
    "          ▝  ███  ▘",
    "             ▝█▘"
  ],
  "parts": [
    "             wwb",
    "             wwi",
    "     bbbbbbbbbibbbbbbbbb",
    "  bbbbb bbbwbbwbbwbbb bbbbb",
    "bbbbb wwwwbwwwwwwwbbwwb bbbbb",
    "bbbbb wiibbbwwwwwbbbbbb bbbbb",
    "  bbbbb bbbwbwwbbwbbb bbbbb",
    "    bbbbbbbbbbibbbbbbbbbb",
    "          b  wwb  b",
    "             wwb"
  ]
}

export const wordmark: LogoArt = {
  "lines": [
    "▜██▙    ▄██▛         ▐██       ▐██ ▗█████████▙         ▐██       ██",
    " ▝▜██▄▗███▘▗██    ▟█▌▐██  ▗▟██▘▐██ ██▛     ▝██▌▗▟█████▙ ██████▙▖ ██",
    "   ▀████▀  ▐██    ██▌▐██▄██▛▀  ▐██ ██▌      ██▌▐██████▀ ██▀▀▀▀██ ██",
    "    ▐██▌   ▐██▖   ██▌▐██▀██▙▖  ▐██ ██▙     ▗██▌▝▀▀▀▀▜██ ██    ██ ██",
    "    ▐██▌    ▜███████▘▐██  ▀██▙▖▐██ ▝█████████▛ ▐██████▛ ██    ██ ██"
  ],
  "parts": [
    "wwww    wwww         www       www bbbbbbbbbbb         bbb       bb",
    " wwwwwwwwwwwww    wwwwww  wwwwwwww bbb     bbbbbbbbbbbb bbbbbbbb bb",
    "   wwwwww  www    wwwwwwwwwww  www bbb      bbbbbbbbbbb bbbbbbbb bb",
    "    wwww   wwww   wwwwwwwwwww  www bbb     bbbbbbbbbbbb bb    bb bb",
    "    wwww    wwwwwwwwwwww  wwwwwwww bbbbbbbbbbb bbbbbbbb bb    bb bb"
  ]
}
